"""Unit tests for Hugging Face discovery, license parsing, and quality scoring."""

import pytest
from src.data.hf_discovery import (
    DatasetCategory,
    DatasetQualityScore,
    HFDatasetDiscovery,
    LicenseStatus,
    ProvenanceStatus,
    RecommendationStatus,
)


def test_license_audit_classification():
    """Verify license categorization across permissive, restricted, and unknown licenses."""
    name, status = HFDatasetDiscovery.audit_license("apache-2.0")
    assert status == LicenseStatus.CLEAR

    name, status = HFDatasetDiscovery.audit_license("MIT")
    assert status == LicenseStatus.CLEAR

    name, status = HFDatasetDiscovery.audit_license("CC-BY-NC-4.0")
    assert status == LicenseStatus.RESTRICTED

    name, status = HFDatasetDiscovery.audit_license("unknown")
    assert status == LicenseStatus.UNKNOWN


def test_provenance_audit_classification():
    """Verify provenance classification handles verified vs scraped vs synthetic."""
    prov, status = HFDatasetDiscovery.audit_provenance("OmilosAISolutions/nyayamitra-training-data")
    assert status == ProvenanceStatus.VERIFIED

    prov, status = HFDatasetDiscovery.audit_provenance("KanoonGPT/indian-case-laws", "Scraped from web")
    assert status == ProvenanceStatus.COMMUNITY_SCRAPED

    prov, status = HFDatasetDiscovery.audit_provenance("dummy/synthetic-cases", "Generated by GPT-4")
    assert status == ProvenanceStatus.SYNTHETIC


def test_quality_score_calculation():
    """Verify composite quality scoring arithmetic."""
    score, breakdown = HFDatasetDiscovery.calculate_quality_score(
        category=DatasetCategory.CASE_LAW,
        license_status=LicenseStatus.CLEAR,
        provenance_status=ProvenanceStatus.VERIFIED,
        has_primary_text=True,
    )
    assert score >= 30.0
    assert len(breakdown) == 8
    assert breakdown["source_authority"] == 5.0
    assert breakdown["license_clarity"] == 5.0
